from fastapi import APIRouter, Query
from db import query_to_dicts

router = APIRouter(prefix="/api/v1", tags=["propensity"])


@router.get("/propensity/scores")
def get_propensity_scores(limit: int = Query(100, le=1000)):
    return query_to_dicts(f"""
        SELECT RESOLVED_ID, TOTAL_IMPRESSIONS, NUM_CHANNELS, JOURNEY_DAYS,
               TOTAL_CLICKS, ACTUAL, PREDICTED_CLASS, PROPENSITY_SCORE
        FROM MTA_DEMO.ANALYTICS.PROPENSITY_SCORES
        ORDER BY PROPENSITY_SCORE DESC
        LIMIT {limit}
    """)


@router.get("/propensity/distribution")
def get_propensity_distribution():
    return query_to_dicts("""
        SELECT 
            FLOOR(PROPENSITY_SCORE * 10) / 10 AS SCORE_BUCKET,
            COUNT(*) AS USER_COUNT,
            SUM(ACTUAL) AS ACTUAL_CONVERTERS,
            ROUND(AVG(ACTUAL), 4) AS CONVERSION_RATE
        FROM MTA_DEMO.ANALYTICS.PROPENSITY_SCORES
        GROUP BY 1
        ORDER BY 1
    """)


@router.get("/propensity/metrics")
def get_propensity_metrics():
    return query_to_dicts("SELECT * FROM MTA_DEMO.ANALYTICS.PROPENSITY_METRICS")


@router.get("/propensity/feature-importance")
def get_feature_importance():
    return query_to_dicts("""
        SELECT 'TOTAL_IMPRESSIONS' AS FEATURE,
               ROUND(CORR(TOTAL_IMPRESSIONS, CONVERTED), 4) AS CORRELATION
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'NUM_CHANNELS', ROUND(CORR(NUM_CHANNELS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'JOURNEY_DAYS', ROUND(CORR(JOURNEY_DAYS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'TOTAL_CLICKS', ROUND(CORR(TOTAL_CLICKS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'SEARCH_IMPRESSIONS', ROUND(CORR(SEARCH_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'SOCIAL_IMPRESSIONS', ROUND(CORR(SOCIAL_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'DISPLAY_IMPRESSIONS', ROUND(CORR(DISPLAY_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'CTV_IMPRESSIONS', ROUND(CORR(CTV_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'OLV_IMPRESSIONS', ROUND(CORR(OLV_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'NATIVE_IMPRESSIONS', ROUND(CORR(NATIVE_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'AUDIO_IMPRESSIONS', ROUND(CORR(AUDIO_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        UNION ALL
        SELECT 'DOOH_IMPRESSIONS', ROUND(CORR(DOOH_IMPRESSIONS, CONVERTED), 4)
        FROM MTA_DEMO.ANALYTICS.USER_FEATURES
        ORDER BY ABS(CORRELATION) DESC
    """)
